language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ctouchdocks/docker-travis-code30 -f Dockerfile.dev .

script:
  - docker run -e CI=true ctouchdocks/docker-travis-code30 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "code30"
  env: "Code30-env"
  bucket_name: "elasticbeanstalk-us-east-2-993937588681"
  bucket_path: "code30"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
